version: '3.8'

services:
  django:
    build: .
    command: >
      sh -c "python manage.py makemigrations book
      && python manage.py makemigrations userprofile
      && python manage.py migrate
      && python manage.py loaddata */fixtures/*.json
      && python manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    container_name: drf_app_dmitry